# Netlify configuration file
# This file configures how Netlify builds and deploys your Vue.js application

[build]
  # The command to build your project
  command = "npm ci && npm run build"
  # The directory that contains the built files to deploy
  publish = "dist"
  # Node.js version to use for the build
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps" }

# Redirect all routes to index.html for Vue Router (SPA)
# This ensures that direct URL access and page refreshes work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for better performance
    Cache-Control = "public, max-age=31536000, immutable"

# Specific cache settings for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache settings for API calls (if you add any)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"
